### ISSUE TITLE
0.3.2 doesn't work with with Om beta4 and react 0.12.2

### ISSUE THREAD

**Issue by mstang** [racehub/om-bootstrap#39]
Everything worked until I upgraded to the latest Om and latest react.  My Nav tabs are now a bunch of random numbers and about 30,000 nodes.  Error messages in my console:

 Warning: React.isValidComponent will be deprecated in a future version. Use React.isValidElement instead.
10574688_1565081647062540_1607884640_n.js:18108 Warning: transferPropsTo is deprecated. See http://fb.me/react-transferpropsto for more information.
10574688_1565081647062540_1607884640_n.js:18108 Warning: createElement(...): Encountered component with a `key` of null. In a future version, this will be treated as equivalent to the string 'null'; instead, provide an explicit key or use undefined.
10574688_1565081647062540_1607884640_n.js:18108 Warning: createElement(...): Encountered component with a `key` of null. In a future version, this will be treated as equivalent to the string 'null'; instead, provide an explicit key or use undefined.
10574688_1565081647062540_1607884640_n.js:18108

**Comment by mstang** [comment]
So, any progress on a fix for this?

**Comment by sritchie** [comment]
@mstang not yet, I've been fully tied up with the holidays - I think I can take a closer look on Monday at #40, which has a half-fix.
