### ISSUE TITLE
navbar with om 0.8.7

### ISSUE THREAD

**Issue by lgrapenthin** [racehub/om-bootstrap#55]
It seems like the navbar breaks pretty badly. It works without navs (is displayed), however 
- :brand key doesn't work with a nested dom element as described in docs - it displays a strange string
- as soon as I use a nav or nav-item, react blows the callstack with traverseAllChildrenImpl

**Comment by lgrapenthin** [comment]
I was mislead by readme. Didn't state that I need 0.4.0-SNAPSHOT. Seems to work flawlessly :+1:

**Comment by sritchie** [comment]
My plan is to do a full release of 0.4.0 this morning. Next time we do a SNAPSHOT test of an upgrade I'll definitely add it to the README. Thanks for the note!



—
