### ISSUE TITLE
Input elements fail schema validation when given optional keys to be passed to child component

### ISSUE THREAD

**Issue by aecay** [racehub/om-bootstrap#59]
When schema validation is turned on, input components cannot be given optional keys to be applied to their child component.  This is because of a missing `t/bootstrap` in the definition of the `Input` schema at <https://github.com/racehub/om-bootstrap/blob/develop/src/om_bootstrap/input.cljs#L39>.

**Comment by sritchie** [comment]
Ah, nice. I know the library doesn't work great with validation turned on. If you've got a setup going to evaluate this, would you mind checking if that change is sufficient and sending me a quick PR? Thanks!

**Comment by aecay** [comment]
Done as #60.
