### ISSUE TITLE
Wrong namespace in pagination example on the components documentation page

### ISSUE THREAD

**Issue by selivanovm** [racehub/om-bootstrap#63]
In the current version of documentation the namespace is written as "om-bootstrap.pager", but it should be "om-bootstrap.pagination".

http://om-bootstrap.herokuapp.com/components

```clojure
(:require [om-bootstrap.pager :as pg])

(pg/pagination {}
  (pg/page {} "1")
  (pg/page {} "2")
  (pg/page {} "3"))

```

**Comment by sritchie** [comment]
Thanks! Fixed in https://github.com/racehub/om-bootstrap/commit/7ef47a0ceabd069a3e9d69f3d0dc4cdc2b067475.

**Comment by sritchie** [comment]
This should hit the doc site in a few minutes.

**Comment by selivanovm** [comment]
Awesome! Thank you for the great library, by the way!

**Comment by sritchie** [comment]
Absolutely, and thanks for the feedback! Let me know if you see anything else we need to tidy up.
