### ISSUE TITLE
Editor settings?

### ISSUE THREAD

**Issue by verma** [racehub/om-bootstrap#65]
Hey,

Sorry this is out of band a little bit, but I was wondering what editor do you use to have code indent right, would you mind sharing the settings if its something like emacs and/or vim?

This is what I get:
```
(render []
        (this is what I get))
```

This is what you have:

```
(render []
  (this is what I get))
```

Thanks,
Uday

**Comment by sritchie** [comment]
No problem! This is a `clojure-mode` thing from emacs. You can get that indenting by adding this to your `.emacs` setup  (mine's at `~/.emacs.d/init.el`)

```elisp
(defvar om-methods
  (list 'render
        'render-state
        'init-state
        'will-mount
        'should-update
        'will-receive-props
        'will-update
        'display-name
        'will-unmount)
  "Methods that should receive sexy clojure indents.")

(dolist (v om-methods)
  (put-clojure-indent v 'defun))
```

Go ahead and add any other methods you like to that list and they'll indent the same way.

**Comment by verma** [comment]
Excellent! Thank you very much!
