### ISSUE TITLE
Dropdown mixin doesn't unregister global event handlers

### ISSUE THREAD

**Issue by brendanyounger** [racehub/om-bootstrap#75]
The function `unbind-root-close-handlers!` calls `map` to unbind the global event handlers for a dropdown, but `map` is lazy, so there is not guarantee they will be called.  Should be `mapv` or `doseq`, etc.

**Comment by sritchie** [comment]
Good call. Does this fix your issue? https://github.com/racehub/om-bootstrap/pull/76

Let me know what you think and I can merge and cut a new release.

Thanks!

**Comment by brendanyounger** [comment]
PR #76 fixes the issue for me.

**Comment by sritchie** [comment]
Okay, excellent. Just pushed 0.5.3.
