### ISSUE TITLE
Control and Identify Collapsible state?

### ISSUE THREAD

**Issue by terhechte** [racehub/om-bootstrap#80]
Hey, I'm using collapsible panels, and they're working great. However, I'd like to be able to see the current collapsible state in my component's render, as well as be able to define the collapsed state from the app state. I.e. I'm currently doing:

``` Clojure
(defcomponent example [state owner opts]
  (render [_]
    (panel/panel {:collapsible? true
                   :header "Example"}
      (dom/span {} "Content"))))
```

And I'd love to be able to do something like this:
``` Clojure
(defcomponent example [state owner opts]
  (render-state [_ s]
    (panel/panel {:collapsible? true
                   :collapsed? (:collapsed state)
                   :header (if (:collapsed? s) "Example Closed" "Example Open")}
      (dom/span {} "Content"))))
```

I.e. change the rendering based on the mixin's current collapsing state *and* change this state based on what may be defined somewhere in my app state. I've just spend an hour trying to achieve this by introspecting the react component's javascript properties, but I couldn't find a way to pull this off.

The possible solution I see is basically re-implementing `panel` within my code base and exposing the functionality somehow. However, before I venture down that road, I thought I'd ask if there's something obvious that I've missed.

Thanks & Cheers,
Benedikt

**Comment by sritchie** [comment]
hey Benedikt,

Yeah, this is something we've run into as well. @dpetrovics did some work recently that may actually solve this issue for you. @dpetrovics ?

**Comment by dpetrovics** [comment]
Hi Benedikt, sorry for the delay in response. Unfortunately right now we store the `collapsed?` attribute in internal component state so you can't view that from the outside. Reimplementing it on your end, or submitting a PR might be your best bet at this point.

**Comment by terhechte** [comment]
Ok, thanks, good to know. I'll have a look at it then.
