### ISSUE TITLE
http://om-bootstrap.herokuapp.com/ down?

### ISSUE THREAD

**Issue by burningTyger** [racehub/om-bootstrap#86]
I get an empty screen.

**Comment by dpetrovics** [comment]
Thanks for this-- I think it's a bug with our version of Clojurescript and the latest Safari (see https://github.com/Prismatic/om-tools/issues/82#issuecomment-146345202). Chrome still seems to be fine. We have to upgrade cljs to fix the issue. I'll try to get around to it soon - PRs also welcome!

**Comment by burningTyger** [comment]
Heard about the Safari bug but I'm using FireFox 42 on Ubuntu. Sorry no PR, just started looking into Clojurescript and whether it fits my needs.

**Comment by dpetrovics** [comment]
Confirmed that this should be fixed by #88 so closing.
